### ISSUE TITLE
Crash when playing <video> (webm) video in HTML/CG

### ISSUE THREAD

**Issue by mistergiantmedia** [rrebuffo/CasparLauncher#10]
First of all, love the launcher. Have been using it for many years!

Found a weird crash, it only happens when you play a {video} . Only tested it with webm video with alpha. I used it for a lowerthird background. Took everything out except the relevent {video} tag while narrowing down the source of the problem.

https://renekok.com/webm_crash/webm.html

I play these commando's over and over:
`PLAY 1-20 [HMTL] "https://renekok.com/webm_crash/webm.html" CUT 1`
`CLEAR 1-20`

At a certain point the HTML producer crashes and the client can't communicate with the server anymore. The server does see the messages coming in in but nothing happens. Sending a commando like CLEAR 1 in the CasparLauncher does work. Also PLAY but the moment you use CG or HTML also the console crashes.

When running Caspar 2.3.3 without CasparLauncher you can see the message in the console (NOT IN THE LOG):
`[0123/154103.181:ERROR:media_internals.cc(114)] Cannot get RenderProcessHost`

But it does not crash the server. So I think that somehow the Server sends it to the Launcher and it does not know what to do with it.

![webm](https://user-images.githubusercontent.com/63671733/214079027-a1c02b43-e0ca-4e38-91be-283b36961d56.jpeg)

**Comment by mistergiantmedia** [comment]
Here you can see the error beging inserted while receiving a command in just the server.
CLEA[ERROR]R [ERROR]1-20

![error](https://user-images.githubusercontent.com/63671733/214081779-151f8b97-9cf8-495f-8997-e960492e636c.jpeg)

**Comment by rrebuffo** [comment]
I can confirm this is a known issue that affects resource intensive templates. A new version of the launcher seems to fix it: I tested it with server version 2.4 and it works flawlessly.
Expect a new beta release sometime in the next few days.

**Comment by rrebuffo** [comment]
Fixed by 43b640924da21044158464744a4fc106689c43b8
