### ISSUE TITLE
Startup commands not issued with Caspar CG v2.4.0 RC 1

### ISSUE THREAD

**Issue by tvt-heikki** [rrebuffo/CasparLauncher#12]
While testing CasparCG server v2.4.0 RC 1 it seems the launcher is unable to issue Startup commands.
Also, issuing commands via the prompt does not work.

Launcher version 1.2.1
Windows 11

**Comment by rrebuffo** [comment]
The new server version uses UTF-8 encoding for the console IO so it breaks the launcher commands (either at startup or manual).
This was fixed in version 2.0 (currently in beta), along with added support for server 2.4 configuration options.

**Comment by tvt-heikki** [comment]
Thanks, moving to launcher v2 fixed the issue.
Great work, btw!
