### ISSUE TITLE
Installation Problems on Offline Server

### ISSUE THREAD

**Issue by slacker3007** [rrebuffo/CasparLauncher#13]
Version: [v2.0-beta: Full app rewrite](https://github.com/rrebuffo/CasparLauncher/releases/tag/v2.0-beta)
I attempted to install the software on two devices: one with internet access and one on an isolated network without internet access.

    Online Device:
        The software installation and launch were successful.
        The installed .NET Runtime is listed as 216MB in Programs and Features.

    Offline Device:
        Installed .NET Desktop Runtime 8.0.6, then tried .NET Runtime 8.0.6.
        When attempting to open the software, an error message indicates additional installation steps are required.
        The installed .NET Runtime is listed as 98.1MB in Programs and Features.

Please advise on how to resolve the installation issue for the offline device.

**Comment by rrebuffo** [comment]
The only runtime needed is .NET Desktop Runtime. It installs .NET Runtime and desktop support.
Did you try the self contained build? Same error?

Also, make sure the offline PC has an active ethernet connection with an IP set. CasparCG had some issues with servers without any NICs active.

**Comment by slacker3007** [comment]
yea, it looks like installing both fixed the issue, thanks
dotnet-runtime-8.0.6-win-x64
windowsdesktop-runtime-8.0.6-win-x64

**Comment by slacker3007** [comment]
After doing more testing and trying it on a fresh server now I have a new issue.
The launcher opens it's minimized and it's not possible to open the UI panel no errors are provided.

https://github.com/rrebuffo/CasparLauncher/assets/23477044/e9de9e00-5f89-4cab-b4d9-0a552f464d59

**Comment by slacker3007** [comment]
After messing around for some time, I decided to connect the server to an open network and install the runtime. The issues persist, so I think it might be hardware-related. I'm not sure what to do now to continue troubleshooting it.

**Comment by slacker3007** [comment]
Workaround was used:
shift + right-click the mouse on the app icon
Maximize the app and resize it to a smaller size

These settings don't reset after Windows restart and the app remembers them, so it always opens like that by default.
