### ISSUE TITLE
Path changes not remembered 

### ISSUE THREAD

**Issue by grahamspr86** [rrebuffo/CasparLauncher#4]
If I change the path to CasparCG or the scanner these aren't remembered when I load CasparLauncher the next time. I'm sure this use to work.

Version 1.0.1

**Comment by rrebuffo** [comment]
If you upgraded from a previous version, please delete the old config files located in the `%AppData%\CasparLauncher\` folder.
There's an issue with .net that won't upgrade the config correctly so starting over is a workaround.

**Comment by grahamspr86** [comment]
> If you upgraded from a previous version, please delete the old config files located in the `%AppData%\CasparLauncher\` folder.
> There's an issue with .net that won't upgrade the config correctly so starting over is a workaround.

Thanks I'll give that a try tomorrow

**Comment by rrebuffo** [comment]
Version 2.x now saves the settings next to CasparLauncher.exe
Unless there's some file corruption, settings will always be loaded and saved correctly.
