### ISSUE TITLE
Can't find server.exe

### ISSUE THREAD

**Issue by slacker3007** [rrebuffo/CasparLauncher#5]
The app wasn't able to find casparcg server.exe and didn't start.
Fixed by rebooting PC.
Comment from rrebuffo in forums:

> "It did happen to me in the past. It is a bug that always forget to fix. It has to do with the windows scaling functions, it throws an error when trying to find the current monitor scale. Logging off and on fixes it."

**Comment by rrebuffo** [comment]
Please check if version 1.2 fixes this issue.
87f6f34afb7a42b9ee9d61b37f8333346d818a71

**Comment by slacker3007** [comment]
Wasn't able to replace the issue, so I assume it was fixed
