### ISSUE TITLE
Request Channel_grid and CCG restart buttons

### ISSUE THREAD

**Issue by slacker3007** [rrebuffo/CasparLauncher#7]
Would be really nice to have channel_grid preview and casparcg restart button on the front UI.
![image](https://user-images.githubusercontent.com/23477044/171410530-e4211c59-8bdb-4a4a-ac80-abc6ddbf0222.png)

**Comment by rrebuffo** [comment]
Added in aff41098bb7879caa4a937200e64ed8ce477f23e and 9fb316305d184cbc31d486e4ac7bdb9e1c0dcaa3
