### ISSUE TITLE
Rquest for startup commands import export

### ISSUE THREAD

**Issue by slacker3007** [rrebuffo/CasparLauncher#8]
Would be good to have better import and export options for startup commands.
As mentioned in the forum:
> It’s saved along with the rest of the settings in %APPDATA%/CasparLauncher/CasparLauncher.exe_[hash]/[version]/user.config but sadly it’s an XML nested inside the settings XML so it will be harder to edit manually.

**Comment by rrebuffo** [comment]
Added copy and paste support (1b9feaa00ea2551e28bb4bfa6cded2f8d31fe572) as a workaround, will be adding file import and export later.

**Comment by Konstantin-Davidneko** [comment]
Added Pull Request with this functionality: https://github.com/rrebuffo/CasparLauncher/pull/9

**Comment by rrebuffo** [comment]
Merged #9
Will be slightly modified ahead of version 2.0
